export const USER_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE'
}

export const ROLE = {
    ADMIN: 'ADMIN',
    MODERATOR: 'MODERATOR',
    MEMBER: 'MEMBER'
}

export const PROVIDER = {
    LOCAL: 'LOCAL',
    GOOGLE: 'GOOGLE',
    BOTH: 'BOTH'
}

export const ACTIVITY_TYPE = {
    MEETING: 'MEETING',
  WORKSHOP: 'WORKSHOP',
  TRAINING: 'TRAINING',
  PERFORMANCE: 'PERFORMANCE',
  COMPETITION: 'COMPETITION',
  SOCIAL: 'SOCIAL',
  VOLUNTEER: 'VOLUNTEER',
}

export const ACTIVITY_STATUS = {
    DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  ONGOING: 'ONGOING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  POSTPONED: 'POSTPONED',
}

export const PARTICIPATION_STATUS = {
    REGISTERED: 'REGISTERED',
  CONFIRMED: 'CONFIRMED',
  ATTENDED: 'ATTENDED',
  ABSENT: 'ABSENT',
  CANCELLED: 'CANCELLED'
}

export const CV_STATUS = {
    PENDING: 'PENDING',
  PASSED: 'PASSED',
  FAILED: 'FAILED'
}

export const FINAL_STATUS = {
  PENDING: 'PENDING',
  PASSED: 'PASSED',
  FAILED: 'FAILED'
}

export const INTERVIEW_STATUS = {
    PENDING: 'PENDING',
  PASSED: 'PASSED',
  FAILED: 'FAILED'
}

export const TASK_STATUS = {
    NEW: 'NEW',
  IN_PROGRESS: 'IN_PROGRESS',
  DONE: 'DONE',
  CANCELLED: 'CANCELLED',
  ON_HOLD: 'ON_HOLD'
}

export const POSITION_LEVEL = {
    MEMBER: 'MEMBER',
  MIDDLE_VICE_HEAD: 'MIDDLE_VICE_HEAD',
  MIDDLE_HEAD: 'MIDDLE_HEAD',
  TOP_VICE_HEAD: 'TOP_VICE_HEAD',
  TOP_HEAD: 'TOP_HEAD'
}